name: rust_functions_bg
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0-277.0.dev
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  html: ^0.15.4
  http: ^1.2.2
  df_rust_interop_web:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - rust_functions/pkg/rust_functions_bg.wasm
